version: "3.7"
services:
  my_service:
    container_name: my_service
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    links:
      - my_service_db
    environment:
      - dev=1
      - db_service_name=my_service_db
      - db_name=example_db
      - db_retry_time=3000
  my_service_db:
    container_name: my_service_db
    image: mongo
    volumes:
    - ./db/data:/data/db
    ports:
      - "27017:27017"